In [14]:
import sys
import time
import config
import re 
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from sklearn.preprocessing import MultiLabelBinarizer

In [15]:
url = config.urlbasecsv
driver = webdriver.Chrome()
driver.get(url)

In [16]:

tabela_remedios = WebDriverWait(driver, 20).until(
    EC.presence_of_all_elements_located((By.CSS_SELECTOR, '#conteudo > div.ato > table:nth-child(21)'))
)

time.sleep(2)

In [17]:
linhas = driver.find_elements(By.CSS_SELECTOR, "table tr")

dados = []
for linha in linhas:
    colunas = [td.text.strip() for td in linha.find_elements(By.TAG_NAME, "td")]
    if colunas:  
        dados.append(colunas)

df = pd.DataFrame(dados)

df.columns = df.iloc[0]
df = df.drop(df.index[0]).reset_index(drop=True)
df.head(30)

,Fármaco,Subgrupo terapêutico ou farmacológico,Forma farmacêutica,Concentração máxima,Indicação terapêutica simplificada
0,Aceclofenaco,M02A – Produtos para dor articular e muscular ...,Creme dermatológico,15 mg/g,Dor e inflamação do sistema musculoesquelético.
1,Acetato de hidrocortisona,D07A – Corticosteroides (isolados) de uso local,"Creme dermatológico, pomada dermatológica",10 mg/g,"Dermatites, eczemas, eritema solar, queimadura..."
2,Acetilcisteína,"R05C – Expectorantes, excluindo associações co...","Comprimido efervescente, granulado",600 mg,Secreções mucosas densas e viscosas nas vias r...
3,Acetilcisteína,R01A – Descongestionantes e outras preparações...,Solução nasal,"11,5 mg/mL",Congestão nasal associada a rinites ou após pr...
4,Acetilcisteína,"R05C – Expectorantes, excluindo associações co...",Solução oral,40 mg/mL,Secreções mucosas densas e viscosas nas vias r...
5,Acetilracemetionina + citrato de colina + betaína,"A05B – Terapia biliar, lipotrópicos",Solução oral,40 + 53 + 50 mg/mL,Auxiliar no tratamento dos distúrbios do fígado
6,Ácido acetilsalicílico,N02B – Analgésicos e antipiréticos,Comprimido,500 mg,"Febre. Dores leves a moderadas, incluindo as a..."
7,Ácido acetilsalicílico,N02B – Analgésicos e antipiréticos,Comprimido revestido de liberação prolongada,500 mg,"Febre. Dores leves a moderadas, incluindo as a..."
8,Ácido acetilsalicílico + ácido ascórbico (Vit. C),N02B – Analgésicos e antipiréticos,Comprimido,400 + 200 mg,"Sintomas da gripe e resfriado comuns, como feb..."
9,Ácido acetilsalicílico + ácido ascórbico (Vit. C),N02B – Analgésicos e antipiréticos,Comprimido efervescente,400 + 240 mg,"Sintomas da gripe e resfriado comuns, como feb..."
10,Ácido acetilsalicílico + cafeína,N02B – Analgésicos e antipiréticos,Comprimido,650 + 65 mg,Dores moderadas a fortes.
11,Ácido acetilsalicílico + maleato de clorfenira...,N02B – Analgésicos e antipiréticos,Cápsula dura,"324 + 2 + 32,4 mg","Sintomas da gripe e resfriado comuns, como feb..."
12,Ácido acetilsalicílico + maleato de dexclorfen...,N02B – Analgésicos e antipiréticos,Comprimido,400 + 1 + 10 + 30 mg,"Sintomas da gripe e resfriado comuns, como feb..."
13,Ácido acetilsalicílico + paracetamol + cafeína,N02B – Analgésicos e antipiréticos,Comprimido revestido,250 + 250 + 65 mg,"Dores leves a moderadas, incluindo as associad..."
14,Ácido azeláico,D10A – Preparações antiacne de uso local,Creme dermatológico,200 mg/g,Acne vulgar.
15,Ácido azeláico,D10A – Preparações antiacne de uso local,Gel dermatológico,150 mg/g,Acne vulgar. Rosácea papulopustulosa.
16,Ácido benzóico + ácido salicílico + iodo metálico,D01A – Antifúngicos de uso local,Solução dermatológica,"20 + 20 + 2,5 mg/mL",Micoses superficiais da pele.
17,Ácido bórico + ácido salicílico + enxofre + óx...,D01A – Antifúngicos de uso local,Pó dermatológico,"3,0 + 0,352 + 17,602 + 11,735 g",Dermatite de fraldas. Brotoeja. Desodorante e ...
18,Ácido salicílico,D11A – Outras preparações dermatológicas,Gel dermatológico,270 mg/g,Tratamento e remoção das verrugas comuns.
19,Ácido undecilênico + undecilenato de sódio + á...,D01A – Antifúngicos de uso local,Solução dermatológica,"40 + 150 + 30 + 50 + 0,5 mg/mL",Micoses superficiais de pele e unha.
20,Ácido undecilênico + undecilenato de zinco + p...,D01A – Antifúngicos de uso local,Pó dermatológico,"2 + 150 + 60 + 0,5 mg/g","Micoses de pele, frieira, de unha, vulvar e pe..."
21,Alantoína + triclosana + óxido de zinco,D01A – Antifúngicos de uso local,Pó dermatológico,5 + 1 + 100 mg/g,"Dermatite de fraldas. Eczemas, brotoejas, quei..."
22,Álcool polivinílico,S01X – Outros produtos oftalmológicos,Solução oftálmica,14 mg/mL,Lubrificante oftálmico / lágrima artificial.
23,Alfaestradiol,G03C – estrógenos,Solução capilar,"0,25 mg/ml",Tratamento e prevenção da alopecia androgenética.
24,Alginato de sódio + bicarbonato de potássio,A02A – Antiácidos,Suspensão oral,100 + 20 mg/mL,"Alívio da regurgitação ácida, azia e dor de es..."
25,Alginato de sódio + bicarbonato de sódio + car...,A02A – Antiácidos,Comprimido mastigável,"250 + 106,5 + 187,5 mg","Alívio da azia, dor de estômago devido à má di..."
26,Alginato de sódio + bicarbonato de sódio + car...,A02A – Antiácidos,Suspensão oral,"50 + 21,3 + 32,5 mg/mL","Alívio da azia, dor de estômago devido à má di..."
27,Bacillus cereus,A07F – Microrganismos antidiarreicos,Suspensão oral,1 X 10^6 end/mL,Coadjuvante no tratamento da diarreia; coadjuv...
28,Bicarbonato de sódio + carbonato de magnésio +...,A02A – Antiácidos,Granulado,"586,742 + 134,34 + 134,34 + 32,495 mg/g",Alívio da azia e dor de estômago devido à má d...
29,Bicarbonato de sódio + carbonato de magnésio +...,A02A – Antiácidos,Pastilha,"63,7 + 67 + 521 + 3,3 mg",Alívio da azia e dor de estômago devido à má d...

In [18]:
df = df[df["Indicação terapêutica simplificada"].notna()].reset_index(drop=True)

In [19]:
def normalizar_indicacao(texto):
    if not isinstance(texto, str):
        return ""

    # tira quebras de linha
    texto = texto.replace("\n", " ").replace("\r", " ")

    # espaços múltiplos -> 1
    texto = re.sub(r"\s+", " ", texto).strip()

    # TROCA vírgula OU ponto por " | "
    # (onde tiver "," ou ".", entra um pipe)
    texto = re.sub(r"[.,]\s*", " | ", texto)

    # pipes duplicados -> apenas um
    texto = re.sub(r"\|\s*\|+", " | ", texto)

    # tira pipe no começo/fim
    texto = texto.strip(" |")

    return texto

In [20]:

df["indicacao_limpa"] = df["Indicação terapêutica simplificada"].apply(normalizar_indicacao)

In [21]:
import re
df["indicacoes_list"] = df["indicacao_limpa"].apply(
    lambda txt: re.split(r"\s*\|\s*", txt) if isinstance(txt, str) and txt.strip() != "" else []
)

# limpar itens vazios
df["indicacoes_list"] = df["indicacoes_list"].apply(
    lambda lista: [s.strip() for s in lista if s.strip() != ""]
)

In [22]:
df["indicacoes_list"].head()

type(df["indicacoes_list"].iloc[0])

list

In [23]:
#one hot agoraaaaa
mlb = MultiLabelBinarizer()

dummies = pd.DataFrame(
    mlb.fit_transform(df["indicacoes_list"]),
    columns=mlb.classes_,
    index=df.index
    ).astype(int)

df_final = pd.concat([df, dummies], axis=1)

df_final.head(10)

,Fármaco,Subgrupo terapêutico ou farmacológico,Forma farmacêutica,Concentração máxima,Indicação terapêutica simplificada,indicacao_limpa,indicacoes_list,Acne vulgar,Afecções cutâneas,Aftas e outras inflamações da mucosa da boca,...,sem catarro,sem catarro associada a gripes e resfriados ou à inalação de agentes irritantes,sob os seios ou em outras áreas da pele que sofrem atrito em crianças e adultos,teníase,tosse e dor muscular associadas à gripes e resfriados,tricuríase,urticárias,vulvar e peniana,vômito e distensão abdominal,Úlcera cutânea
0,Aceclofenaco,M02A – Produtos para dor articular e muscular ...,Creme dermatológico,15 mg/g,Dor e inflamação do sistema musculoesquelético.,Dor e inflamação do sistema musculoesquelético,[Dor e inflamação do sistema musculoesquelético],0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Acetato de hidrocortisona,D07A – Corticosteroides (isolados) de uso local,"Creme dermatológico, pomada dermatológica",10 mg/g,"Dermatites, eczemas, eritema solar, queimadura...",Dermatites | eczemas | eritema solar | queimad...,"[Dermatites, eczemas, eritema solar, queimadur...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Acetilcisteína,"R05C – Expectorantes, excluindo associações co...","Comprimido efervescente, granulado",600 mg,Secreções mucosas densas e viscosas nas vias r...,Secreções mucosas densas e viscosas nas vias r...,[Secreções mucosas densas e viscosas nas vias ...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Acetilcisteína,R01A – Descongestionantes e outras preparações...,Solução nasal,"11,5 mg/mL",Congestão nasal associada a rinites ou após pr...,Congestão nasal associada a rinites ou após pr...,[Congestão nasal associada a rinites ou após p...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Acetilcisteína,"R05C – Expectorantes, excluindo associações co...",Solução oral,40 mg/mL,Secreções mucosas densas e viscosas nas vias r...,Secreções mucosas densas e viscosas nas vias r...,[Secreções mucosas densas e viscosas nas vias ...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Acetilracemetionina + citrato de colina + betaína,"A05B – Terapia biliar, lipotrópicos",Solução oral,40 + 53 + 50 mg/mL,Auxiliar no tratamento dos distúrbios do fígado,Auxiliar no tratamento dos distúrbios do fígado,[Auxiliar no tratamento dos distúrbios do fígado],0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Ácido acetilsalicílico,N02B – Analgésicos e antipiréticos,Comprimido,500 mg,"Febre. Dores leves a moderadas, incluindo as a...",Febre | Dores leves a moderadas | incluindo as...,"[Febre, Dores leves a moderadas, incluindo as ...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,Ácido acetilsalicílico,N02B – Analgésicos e antipiréticos,Comprimido revestido de liberação prolongada,500 mg,"Febre. Dores leves a moderadas, incluindo as a...",Febre | Dores leves a moderadas | incluindo as...,"[Febre, Dores leves a moderadas, incluindo as ...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Ácido acetilsalicílico + ácido ascórbico (Vit. C),N02B – Analgésicos e antipiréticos,Comprimido,400 + 200 mg,"Sintomas da gripe e resfriado comuns, como feb...",Sintomas da gripe e resfriado comuns | como fe...,"[Sintomas da gripe e resfriado comuns, como fe...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Ácido acetilsalicílico + ácido ascórbico (Vit. C),N02B – Analgésicos e antipiréticos,Comprimido efervescente,400 + 240 mg,"Sintomas da gripe e resfriado comuns, como feb...",Sintomas da gripe e resfriado comuns | como fe...,"[Sintomas da gripe e resfriado comuns, como fe...",0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
colunas = list(dummies.columns)
for c in colunas:
    print(c)

Acne vulgar
Afecções cutâneas
Aftas e outras inflamações da mucosa da boca
Aftas e outras inflamações na mucosa da boca
Alívio da azia
Alívio da azia devido à má digestão
Alívio da azia e dor de estômago devido à má digestão
Alívio da dor de dente
Alívio da regurgitação ácida
Alívio de cólicas gastrintestinais
Alívio de sintomas frequentes (que ocorrem por dois ou mais dias na semana) de azia e queimação
Alívio dos deconfortos bucais da primeira dentição
Ascaridíase
Auxiliar no processo de mineralização óssea
Auxiliar no tratamento dos distúrbios do fígado
Brotoeja
Brotoejas
Candidíase vaginal
Candidíase vaginal e perianal
Candisíase vaginal e peniana
Caspa
Cefaleia
Cefaleia e alergias
Cefaleia e enxaqueca
Coadjuvante no tratamento da diarreia; coadjuvante em enterocolites crônicas e agudas
Congestão nasal
Congestão nasal associada a rinites ou após procedimentos cirúrgicos no nariz
Congestão nasal e tosse associadas a gripes e resfriados
Conjutivite alérgica
Constipação intestinal ou diarreia associadas a condições como diverticulose e síndrome do intestino irritável
Curativo após cirurgias proctológicas
Dependência do tabaco
Dermatite atópica
Dermatite de fraldas
Dermatite seborreica
Dermatites
Desodorante e antiperspirante de axilas e pés
Desodorante e antiperspirante de pés e axilas
Desodorante e antiperspirante dos pés e axilas
Diarreias de diferentes causas
Dor
Dor associada a contraturas musculares
Dor de garganta
Dor de ouvido
Dor e febre
Dor e inflamação do sistema musculoesquelético
Dores agudas causadas por inflamação; dor e febre
Dores leves a moderadas
Dores leves a moderadas associadas a contraturas musculares
Dores moderadas a fortes
Dores musculares leves a moderadas
Eczemas
Eczemas e queimaduras infectados
Eczemas/dermatites alérgicos
Enterobíase
Escabiose
Escaras
Espessamento da pele
Estado de fraqueza e diminuição do apetite
Estimulante do apetite
Febre
Febre e dores leves a moderadas
Ferimentos leves e escoriações
Ferimentos superficiais na pele
Fissuras
Fissuras da pele
Fissuras de pele e mucosas
Flebites e tromboflebites superficiais
Hematomas e inflamação provocada por varizes e em processos inflamatórios localizados
Hemorroidas
Hemorroidas internas e externas
Higiene dos olhos
Higienização das mãos e corpo
Infecções bacterianas da pele e mucosas
Inflamação da garganta
Inflamações e dores na mucosa da boca
Inflamações e dores na mucosa da boca e garganta
Irritação e prurido oculares causados por exposição a agentes irritantes
Irritações da garganta
Irritações da pele
Irritações da pele de pequena intensidade provocadas pela exposição ao sol
Irritações da pele de pequena intensidade provocadas pelo vento ou exposição prolongada ao sol
Irritações na região dos órgãos genitais e das nádegas
Laxante leve
Laxativo
Lubrificante oftálmico / lágrima artificial
Micoses de pele
Micoses de unha
Micoses superficiais da pele
Micoses superficiais de pele
Micoses superficiais de pele e unha
Micoses superficiais de pele e unha e infecções mistas por fungos e bactérias
Mucosa nasal ressecada e irritada
Oleosidade do couro cabeludo
Pediculose
Pele seca e áspera
Períodos de convalescença
Picada de insetos
Prevenção de frieiras e pruridos na pele
Prisão de ventre
Profilaxia da cárie
Profilaxia de infecções cutâneomucosas decorrentes de ferimentos cortantes
Profilaxia e tratamento da cinetose
Prurido
Regularização do hábito intestinal
Reidratação ou manutenção da hidratação na diarreia aguda
Remoção de cerume
Restauração da flora intestinal
Rinite alérgica
Rosácea
Rosácea papulopustulosa
Secreções mucosas densas e viscosas nas vias respiratórias
Sintomas da gripe e resfriado comuns
Sintomas da rinite alérgica
Sintomas da síndrome de abstinência de nicotina
Sintomas de distúrbios do estado geral decorrentes de alterações climáticas e de abuso de álcool ou nicotina
Sintomas de gripe
Sintomas de urticária ou alergias de pele
Sob orientação de profissional de saúde: preparo diagnóstico ou cirúrgico
Tosse
Tosse associada a gripes e resfriados
Tosse com ou sem catarro associada a gripes e resfriados
Tosse seca
Tratamento de infecções fúngicas das unhas
Tratamento e prevenção da alopecia androgenética
Tratamento e remoção das verrugas comuns
Tratamento tópico de herpes labial
Urticária
alérgicas ou não
ancilostomíase
ardor
ascaridíase
azia e dor de estômago devido à má digestão
azia e dor de estômago devido à má digestão e distensão abdominal
brotoejas
candidíase vulvar e peniana
candidíase vulvar e peniana e infecções mistas por fungos e bactérias
cefaleia
cefaleia e coriza
como febre
como febre e cefaleia
como impetigo e furúnculo
coriza e congestão nasal
cotovelos
das vias biliares
de unha
decorrentes ou associadas a doenças broncopulmonares
dermatite seborreica
desconforto para urinar
dismenorreias e mialgias em adultos
dor
dor de dente
dor de estômago devido à má digestão
dor de estômago e cefaleia devido à má digestão
dor de garganta
dor no corpo
dor pós escleroterapia venosa
dorsalgia
dos órgãos sexuais e das vias urinárias
eczema e calosidade de mãos
eczemas
enjoo e vômito
enjôo
enjôo e vômito
entre os dedos
enxaqueca e cólicas abdominais
enxaqueca e traumatismos
eritema solar
eructação e flatuência
escabiose
escaras
faringites
ferimentos leves e escaras
ferimentos leves e escoriações
frieira
frieiras
ftiríase
hematomas e contusões
incluindo as associadas a gripes e resfriados comuns
incluindo as associadas a gripes e resfriados comuns e traumatismos
incluindo as associadas com cólicas menstruais e a gripes e resfriados comuns
incluindo as associadas com gripes e resfriados comuns
incluindo cefaleia tensional
incluindo às associadas a sintomas de gripe e resfriado; dores musculares e articulares; dor após traumas
infestações por carrapatos
joelhos e pés
língua e garganta
micose superficial do couro cabeludo
musculares
nas axilas
necatoríase
picadas de insetos
pitiríase versicolor
prurido e eczemas da região do ânus
psoríase e eczema do couro cabeludo
queimadura de primeiro grau e picadas de inseto
queimaduras e outras irritações superficiais da pele
resfriado
ressecamento e descamação da pele
rinite e sinusite
sem catarro
sem catarro associada a gripes e resfriados ou à inalação de agentes irritantes
sob os seios ou em outras áreas da pele que sofrem atrito em crianças e adultos
teníase
tosse e dor muscular associadas à gripes e resfriados
tricuríase
urticárias
vulvar e peniana
vômito e distensão abdominal
Úlcera cutânea

In [25]:
mapeamento_colunas = {col: col for col in dummies.columns}
print(mapeamento_colunas)

{'Acne vulgar': 'Acne vulgar', 'Afecções cutâneas': 'Afecções cutâneas', 'Aftas e outras inflamações da mucosa da boca': 'Aftas e outras inflamações da mucosa da boca', 'Aftas e outras inflamações na mucosa da boca': 'Aftas e outras inflamações na mucosa da boca', 'Alívio da azia': 'Alívio da azia', 'Alívio da azia devido à má digestão': 'Alívio da azia devido à má digestão', 'Alívio da azia e dor de estômago devido à má digestão': 'Alívio da azia e dor de estômago devido à má digestão', 'Alívio da dor de dente': 'Alívio da dor de dente', 'Alívio da regurgitação ácida': 'Alívio da regurgitação ácida', 'Alívio de cólicas gastrintestinais': 'Alívio de cólicas gastrintestinais', 'Alívio de sintomas frequentes (que ocorrem por dois ou mais dias na semana) de azia e queimação': 'Alívio de sintomas frequentes (que ocorrem por dois ou mais dias na semana) de azia e queimação', 'Alívio dos deconfortos bucais da primeira dentição': 'Alívio dos deconfortos bucais da primeira dentição', 'Ascaridíase': 'Ascaridíase', 'Auxiliar no processo de mineralização óssea': 'Auxiliar no processo de mineralização óssea', 'Auxiliar no tratamento dos distúrbios do fígado': 'Auxiliar no tratamento dos distúrbios do fígado', 'Brotoeja': 'Brotoeja', 'Brotoejas': 'Brotoejas', 'Candidíase vaginal': 'Candidíase vaginal', 'Candidíase vaginal e perianal': 'Candidíase vaginal e perianal', 'Candisíase vaginal e peniana': 'Candisíase vaginal e peniana', 'Caspa': 'Caspa', 'Cefaleia': 'Cefaleia', 'Cefaleia e alergias': 'Cefaleia e alergias', 'Cefaleia e enxaqueca': 'Cefaleia e enxaqueca', 'Coadjuvante no tratamento da diarreia; coadjuvante em enterocolites crônicas e agudas': 'Coadjuvante no tratamento da diarreia; coadjuvante em enterocolites crônicas e agudas', 'Congestão nasal': 'Congestão nasal', 'Congestão nasal associada a rinites ou após procedimentos cirúrgicos no nariz': 'Congestão nasal associada a rinites ou após procedimentos cirúrgicos no nariz', 'Congestão nasal e tosse associadas a gripes e resfriados': 'Congestão nasal e tosse associadas a gripes e resfriados', 'Conjutivite alérgica': 'Conjutivite alérgica', 'Constipação intestinal ou diarreia associadas a condições como diverticulose e síndrome do intestino irritável': 'Constipação intestinal ou diarreia associadas a condições como diverticulose e síndrome do intestino irritável', 'Curativo após cirurgias proctológicas': 'Curativo após cirurgias proctológicas', 'Dependência do tabaco': 'Dependência do tabaco', 'Dermatite atópica': 'Dermatite atópica', 'Dermatite de fraldas': 'Dermatite de fraldas', 'Dermatite seborreica': 'Dermatite seborreica', 'Dermatites': 'Dermatites', 'Desodorante e antiperspirante de axilas e pés': 'Desodorante e antiperspirante de axilas e pés', 'Desodorante e antiperspirante de pés e axilas': 'Desodorante e antiperspirante de pés e axilas', 'Desodorante e antiperspirante dos pés e axilas': 'Desodorante e antiperspirante dos pés e axilas', 'Diarreias de diferentes causas': 'Diarreias de diferentes causas', 'Dor': 'Dor', 'Dor associada a contraturas musculares': 'Dor associada a contraturas musculares', 'Dor de garganta': 'Dor de garganta', 'Dor de ouvido': 'Dor de ouvido', 'Dor e febre': 'Dor e febre', 'Dor e inflamação do sistema musculoesquelético': 'Dor e inflamação do sistema musculoesquelético', 'Dores agudas causadas por inflamação; dor e febre': 'Dores agudas causadas por inflamação; dor e febre', 'Dores leves a moderadas': 'Dores leves a moderadas', 'Dores leves a moderadas associadas a contraturas musculares': 'Dores leves a moderadas associadas a contraturas musculares', 'Dores moderadas a fortes': 'Dores moderadas a fortes', 'Dores musculares leves a moderadas': 'Dores musculares leves a moderadas', 'Eczemas': 'Eczemas', 'Eczemas e queimaduras infectados': 'Eczemas e queimaduras infectados', 'Eczemas/dermatites alérgicos': 'Eczemas/dermatites alérgicos', 'Enterobíase': 'Enterobíase', 'Escabiose': 'Escabiose', 'Escaras': 'Escaras', 'Espessamento da pele': 'Espessamento da pele', 'Estado de fraqueza e diminuição do apetite': 'Estado de fraqueza e diminuição do apetite', 'Estimulante do apetite': 'Estimulante do apetite', 'Febre': 'Febre', 'Febre e dores leves a moderadas': 'Febre e dores leves a moderadas', 'Ferimentos leves e escoriações': 'Ferimentos leves e escoriações', 'Ferimentos superficiais na pele': 'Ferimentos superficiais na pele', 'Fissuras': 'Fissuras', 'Fissuras da pele': 'Fissuras da pele', 'Fissuras de pele e mucosas': 'Fissuras de pele e mucosas', 'Flebites e tromboflebites superficiais': 'Flebites e tromboflebites superficiais', 'Hematomas e inflamação provocada por varizes e em processos inflamatórios localizados': 'Hematomas e inflamação provocada por varizes e em processos inflamatórios localizados', 'Hemorroidas': 'Hemorroidas', 'Hemorroidas internas e externas': 'Hemorroidas internas e externas', 'Higiene dos olhos': 'Higiene dos olhos', 'Higienização das mãos e corpo': 'Higienização das mãos e corpo', 'Infecções bacterianas da pele e mucosas': 'Infecções bacterianas da pele e mucosas', 'Inflamação da garganta': 'Inflamação da garganta', 'Inflamações e dores na mucosa da boca': 'Inflamações e dores na mucosa da boca', 'Inflamações e dores na mucosa da boca e garganta': 'Inflamações e dores na mucosa da boca e garganta', 'Irritação e prurido oculares causados por exposição a agentes irritantes': 'Irritação e prurido oculares causados por exposição a agentes irritantes', 'Irritações da garganta': 'Irritações da garganta', 'Irritações da pele': 'Irritações da pele', 'Irritações da pele de pequena intensidade provocadas pela exposição ao sol': 'Irritações da pele de pequena intensidade provocadas pela exposição ao sol', 'Irritações da pele de pequena intensidade provocadas pelo vento ou exposição prolongada ao sol': 'Irritações da pele de pequena intensidade provocadas pelo vento ou exposição prolongada ao sol', 'Irritações na região dos órgãos genitais e das nádegas': 'Irritações na região dos órgãos genitais e das nádegas', 'Laxante leve': 'Laxante leve', 'Laxativo': 'Laxativo', 'Lubrificante oftálmico / lágrima artificial': 'Lubrificante oftálmico / lágrima artificial', 'Micoses de pele': 'Micoses de pele', 'Micoses de unha': 'Micoses de unha', 'Micoses superficiais da pele': 'Micoses superficiais da pele', 'Micoses superficiais de pele': 'Micoses superficiais de pele', 'Micoses superficiais de pele e unha': 'Micoses superficiais de pele e unha', 'Micoses superficiais de pele e unha e infecções mistas por fungos e bactérias': 'Micoses superficiais de pele e unha e infecções mistas por fungos e bactérias', 'Mucosa nasal ressecada e irritada': 'Mucosa nasal ressecada e irritada', 'Oleosidade do couro cabeludo': 'Oleosidade do couro cabeludo', 'Pediculose': 'Pediculose', 'Pele seca e áspera': 'Pele seca e áspera', 'Períodos de convalescença': 'Períodos de convalescença', 'Picada de insetos': 'Picada de insetos', 'Prevenção de frieiras e pruridos na pele': 'Prevenção de frieiras e pruridos na pele', 'Prisão de ventre': 'Prisão de ventre', 'Profilaxia da cárie': 'Profilaxia da cárie', 'Profilaxia de infecções cutâneomucosas decorrentes de ferimentos cortantes': 'Profilaxia de infecções cutâneomucosas decorrentes de ferimentos cortantes', 'Profilaxia e tratamento da cinetose': 'Profilaxia e tratamento da cinetose', 'Prurido': 'Prurido', 'Regularização do hábito intestinal': 'Regularização do hábito intestinal', 'Reidratação ou manutenção da hidratação na diarreia aguda': 'Reidratação ou manutenção da hidratação na diarreia aguda', 'Remoção de cerume': 'Remoção de cerume', 'Restauração da flora intestinal': 'Restauração da flora intestinal', 'Rinite alérgica': 'Rinite alérgica', 'Rosácea': 'Rosácea', 'Rosácea papulopustulosa': 'Rosácea papulopustulosa', 'Secreções mucosas densas e viscosas nas vias respiratórias': 'Secreções mucosas densas e viscosas nas vias respiratórias', 'Sintomas da gripe e resfriado comuns': 'Sintomas da gripe e resfriado comuns', 'Sintomas da rinite alérgica': 'Sintomas da rinite alérgica', 'Sintomas da síndrome de abstinência de nicotina': 'Sintomas da síndrome de abstinência de nicotina', 'Sintomas de distúrbios do estado geral decorrentes de alterações climáticas e de abuso de álcool ou nicotina': 'Sintomas de distúrbios do estado geral decorrentes de alterações climáticas e de abuso de álcool ou nicotina', 'Sintomas de gripe': 'Sintomas de gripe', 'Sintomas de urticária ou alergias de pele': 'Sintomas de urticária ou alergias de pele', 'Sob orientação de profissional de saúde: preparo diagnóstico ou cirúrgico': 'Sob orientação de profissional de saúde: preparo diagnóstico ou cirúrgico', 'Tosse': 'Tosse', 'Tosse associada a gripes e resfriados': 'Tosse associada a gripes e resfriados', 'Tosse com ou sem catarro associada a gripes e resfriados': 'Tosse com ou sem catarro associada a gripes e resfriados', 'Tosse seca': 'Tosse seca', 'Tratamento de infecções fúngicas das unhas': 'Tratamento de infecções fúngicas das unhas', 'Tratamento e prevenção da alopecia androgenética': 'Tratamento e prevenção da alopecia androgenética', 'Tratamento e remoção das verrugas comuns': 'Tratamento e remoção das verrugas comuns', 'Tratamento tópico de herpes labial': 'Tratamento tópico de herpes labial', 'Urticária': 'Urticária', 'alérgicas ou não': 'alérgicas ou não', 'ancilostomíase': 'ancilostomíase', 'ardor': 'ardor', 'ascaridíase': 'ascaridíase', 'azia e dor de estômago devido à má digestão': 'azia e dor de estômago devido à má digestão', 'azia e dor de estômago devido à má digestão e distensão abdominal': 'azia e dor de estômago devido à má digestão e distensão abdominal', 'brotoejas': 'brotoejas', 'candidíase vulvar e peniana': 'candidíase vulvar e peniana', 'candidíase vulvar e peniana e infecções mistas por fungos e bactérias': 'candidíase vulvar e peniana e infecções mistas por fungos e bactérias', 'cefaleia': 'cefaleia', 'cefaleia e coriza': 'cefaleia e coriza', 'como febre': 'como febre', 'como febre e cefaleia': 'como febre e cefaleia', 'como impetigo e furúnculo': 'como impetigo e furúnculo', 'coriza e congestão nasal': 'coriza e congestão nasal', 'cotovelos': 'cotovelos', 'das vias biliares': 'das vias biliares', 'de unha': 'de unha', 'decorrentes ou associadas a doenças broncopulmonares': 'decorrentes ou associadas a doenças broncopulmonares', 'dermatite seborreica': 'dermatite seborreica', 'desconforto para urinar': 'desconforto para urinar', 'dismenorreias e mialgias em adultos': 'dismenorreias e mialgias em adultos', 'dor': 'dor', 'dor de dente': 'dor de dente', 'dor de estômago devido à má digestão': 'dor de estômago devido à má digestão', 'dor de estômago e cefaleia devido à má digestão': 'dor de estômago e cefaleia devido à má digestão', 'dor de garganta': 'dor de garganta', 'dor no corpo': 'dor no corpo', 'dor pós escleroterapia venosa': 'dor pós escleroterapia venosa', 'dorsalgia': 'dorsalgia', 'dos órgãos sexuais e das vias urinárias': 'dos órgãos sexuais e das vias urinárias', 'eczema e calosidade de mãos': 'eczema e calosidade de mãos', 'eczemas': 'eczemas', 'enjoo e vômito': 'enjoo e vômito', 'enjôo': 'enjôo', 'enjôo e vômito': 'enjôo e vômito', 'entre os dedos': 'entre os dedos', 'enxaqueca e cólicas abdominais': 'enxaqueca e cólicas abdominais', 'enxaqueca e traumatismos': 'enxaqueca e traumatismos', 'eritema solar': 'eritema solar', 'eructação e flatuência': 'eructação e flatuência', 'escabiose': 'escabiose', 'escaras': 'escaras', 'faringites': 'faringites', 'ferimentos leves e escaras': 'ferimentos leves e escaras', 'ferimentos leves e escoriações': 'ferimentos leves e escoriações', 'frieira': 'frieira', 'frieiras': 'frieiras', 'ftiríase': 'ftiríase', 'hematomas e contusões': 'hematomas e contusões', 'incluindo as associadas a gripes e resfriados comuns': 'incluindo as associadas a gripes e resfriados comuns', 'incluindo as associadas a gripes e resfriados comuns e traumatismos': 'incluindo as associadas a gripes e resfriados comuns e traumatismos', 'incluindo as associadas com cólicas menstruais e a gripes e resfriados comuns': 'incluindo as associadas com cólicas menstruais e a gripes e resfriados comuns', 'incluindo as associadas com gripes e resfriados comuns': 'incluindo as associadas com gripes e resfriados comuns', 'incluindo cefaleia tensional': 'incluindo cefaleia tensional', 'incluindo às associadas a sintomas de gripe e resfriado; dores musculares e articulares; dor após traumas': 'incluindo às associadas a sintomas de gripe e resfriado; dores musculares e articulares; dor após traumas', 'infestações por carrapatos': 'infestações por carrapatos', 'joelhos e pés': 'joelhos e pés', 'língua e garganta': 'língua e garganta', 'micose superficial do couro cabeludo': 'micose superficial do couro cabeludo', 'musculares': 'musculares', 'nas axilas': 'nas axilas', 'necatoríase': 'necatoríase', 'picadas de insetos': 'picadas de insetos', 'pitiríase versicolor': 'pitiríase versicolor', 'prurido e eczemas da região do ânus': 'prurido e eczemas da região do ânus', 'psoríase e eczema do couro cabeludo': 'psoríase e eczema do couro cabeludo', 'queimadura de primeiro grau e picadas de inseto': 'queimadura de primeiro grau e picadas de inseto', 'queimaduras e outras irritações superficiais da pele': 'queimaduras e outras irritações superficiais da pele', 'resfriado': 'resfriado', 'ressecamento e descamação da pele': 'ressecamento e descamação da pele', 'rinite e sinusite': 'rinite e sinusite', 'sem catarro': 'sem catarro', 'sem catarro associada a gripes e resfriados ou à inalação de agentes irritantes': 'sem catarro associada a gripes e resfriados ou à inalação de agentes irritantes', 'sob os seios ou em outras áreas da pele que sofrem atrito em crianças e adultos': 'sob os seios ou em outras áreas da pele que sofrem atrito em crianças e adultos', 'teníase': 'teníase', 'tosse e dor muscular associadas à gripes e resfriados': 'tosse e dor muscular associadas à gripes e resfriados', 'tricuríase': 'tricuríase', 'urticárias': 'urticárias', 'vulvar e peniana': 'vulvar e peniana', 'vômito e distensão abdominal': 'vômito e distensão abdominal', 'Úlcera cutânea': 'Úlcera cutânea'}

In [26]:
import unidecode

In [27]:
import re

def encode_nome(s: str) -> str:
    s = s.lower().strip()
    s = unidecode.unidecode(s)            # tira acentos
    s = re.sub(r'[^a-z0-9]+', '_', s)     # tudo que não é letra/numero vira _
    s = re.sub(r'_+', '_', s)             # colapsa vários ___ em _
    s = s.strip('_')                      # tira _ do começo/fim
    return s 

# resumindo  snake_case

In [28]:
edit_colunas = {orig: encode_nome(orig) for orig in mapeamento_colunas.keys()}

In [29]:
dummies = dummies.rename(columns=edit_colunas)

In [30]:
print(dummies)

     acne_vulgar  afeccoes_cutaneas  \
0              0                  0
1              0                  0
2              0                  0
3              0                  0
4              0                  0
..           ...                ...
259            0                  0
260            0                  0
261            0                  0
262            0                  0
263            0                  0

     aftas_e_outras_inflamacoes_da_mucosa_da_boca  \
0                                               0
1                                               0
2                                               0
3                                               0
4                                               0
..                                            ...
259                                             0
260                                             0
261                                             0
262                                             0
263                                             0

     aftas_e_outras_inflamacoes_na_mucosa_da_boca  alivio_da_azia  \
0                                               0               0
1                                               0               0
2                                               0               0
3                                               0               0
4                                               0               0
..                                            ...             ...
259                                             1               0
260                                             1               0
261                                             0               0
262                                             0               0
263                                             0               0

     alivio_da_azia_devido_a_ma_digestao  \
0                                      0
1                                      0
2                                      0
3                                      0
4                                      0
..                                   ...
259                                    0
260                                    0
261                                    0
262                                    0
263                                    0

     alivio_da_azia_e_dor_de_estomago_devido_a_ma_digestao  \
0                                                    0
1                                                    0
2                                                    0
3                                                    0
4                                                    0
..                                                 ...
259                                                  0
260                                                  0
261                                                  0
262                                                  0
263                                                  0

     alivio_da_dor_de_dente  alivio_da_regurgitacao_acida  \
0                         0                             0
1                         0                             0
2                         0                             0
3                         0                             0
4                         0                             0
..                      ...                           ...
259                       0                             0
260                       0                             0
261                       0                             0
262                       0                             0
263                       0                             0

     alivio_de_colicas_gastrintestinais  ...  sem_catarro  \
0                                     0  ...            0
1                                     0  ...            0
2                                     0  ...            0
3                                     0  ...            0
4                                     0  ...            0
..                                  ...  ...          ...
259                                   0  ...            0
260                                   0  ...            0
261                                   0  ...            0
262                                   0  ...            0
263                                   0  ...            0

     sem_catarro_associada_a_gripes_e_resfriados_ou_a_inalacao_de_agentes_irritantes  \
0                                                    0
1                                                    0
2                                                    0
3                                                    0
4                                                    0
..                                                 ...
259                                                  0
260                                                  0
261                                                  0
262                                                  0
263                                                  0

     sob_os_seios_ou_em_outras_areas_da_pele_que_sofrem_atrito_em_criancas_e_adultos  \
0                                                    0
1                                                    0
2                                                    0
3                                                    0
4                                                    0
..                                                 ...
259                                                  0
260                                                  0
261                                                  0
262                                                  0
263                                                  0

     teniase  tosse_e_dor_muscular_associadas_a_gripes_e_resfriados  \
0          0                                                  0
1          0                                                  0
2          0                                                  0
3          0                                                  0
4          0                                                  0
..       ...                                                ...
259        0                                                  0
260        0                                                  0
261        0                                                  0
262        0                                                  0
263        0                                                  0

     tricuriase  urticarias  vulvar_e_peniana  vomito_e_distensao_abdominal  \
0             0           0                 0                             0
1             0           0                 0                             0
2             0           0                 0                             0
3             0           0                 0                             0
4             0           0                 0                             0
..          ...         ...               ...                           ...
259           0           0                 0                             0
260           0           0                 0                             0
261           0           0                 0                             0
262           0           0                 0                             0
263           0           0                 0                             0

     ulcera_cutanea
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
259               0
260               0
261               0
262               0
263               0

[264 rows x 210 columns]

In [31]:
df_final = pd.concat([df, dummies], axis=1)

In [32]:
df_final.head(30)

,Fármaco,Subgrupo terapêutico ou farmacológico,Forma farmacêutica,Concentração máxima,Indicação terapêutica simplificada,indicacao_limpa,indicacoes_list,acne_vulgar,afeccoes_cutaneas,aftas_e_outras_inflamacoes_da_mucosa_da_boca,...,sem_catarro,sem_catarro_associada_a_gripes_e_resfriados_ou_a_inalacao_de_agentes_irritantes,sob_os_seios_ou_em_outras_areas_da_pele_que_sofrem_atrito_em_criancas_e_adultos,teniase,tosse_e_dor_muscular_associadas_a_gripes_e_resfriados,tricuriase,urticarias,vulvar_e_peniana,vomito_e_distensao_abdominal,ulcera_cutanea
0,Aceclofenaco,M02A – Produtos para dor articular e muscular ...,Creme dermatológico,15 mg/g,Dor e inflamação do sistema musculoesquelético.,Dor e inflamação do sistema musculoesquelético,[Dor e inflamação do sistema musculoesquelético],0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Acetato de hidrocortisona,D07A – Corticosteroides (isolados) de uso local,"Creme dermatológico, pomada dermatológica",10 mg/g,"Dermatites, eczemas, eritema solar, queimadura...",Dermatites | eczemas | eritema solar | queimad...,"[Dermatites, eczemas, eritema solar, queimadur...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Acetilcisteína,"R05C – Expectorantes, excluindo associações co...","Comprimido efervescente, granulado",600 mg,Secreções mucosas densas e viscosas nas vias r...,Secreções mucosas densas e viscosas nas vias r...,[Secreções mucosas densas e viscosas nas vias ...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Acetilcisteína,R01A – Descongestionantes e outras preparações...,Solução nasal,"11,5 mg/mL",Congestão nasal associada a rinites ou após pr...,Congestão nasal associada a rinites ou após pr...,[Congestão nasal associada a rinites ou após p...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Acetilcisteína,"R05C – Expectorantes, excluindo associações co...",Solução oral,40 mg/mL,Secreções mucosas densas e viscosas nas vias r...,Secreções mucosas densas e viscosas nas vias r...,[Secreções mucosas densas e viscosas nas vias ...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Acetilracemetionina + citrato de colina + betaína,"A05B – Terapia biliar, lipotrópicos",Solução oral,40 + 53 + 50 mg/mL,Auxiliar no tratamento dos distúrbios do fígado,Auxiliar no tratamento dos distúrbios do fígado,[Auxiliar no tratamento dos distúrbios do fígado],0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Ácido acetilsalicílico,N02B – Analgésicos e antipiréticos,Comprimido,500 mg,"Febre. Dores leves a moderadas, incluindo as a...",Febre | Dores leves a moderadas | incluindo as...,"[Febre, Dores leves a moderadas, incluindo as ...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,Ácido acetilsalicílico,N02B – Analgésicos e antipiréticos,Comprimido revestido de liberação prolongada,500 mg,"Febre. Dores leves a moderadas, incluindo as a...",Febre | Dores leves a moderadas | incluindo as...,"[Febre, Dores leves a moderadas, incluindo as ...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Ácido acetilsalicílico + ácido ascórbico (Vit. C),N02B – Analgésicos e antipiréticos,Comprimido,400 + 200 mg,"Sintomas da gripe e resfriado comuns, como feb...",Sintomas da gripe e resfriado comuns | como fe...,"[Sintomas da gripe e resfriado comuns, como fe...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Ácido acetilsalicílico + ácido ascórbico (Vit. C),N02B – Analgésicos e antipiréticos,Comprimido efervescente,400 + 240 mg,"Sintomas da gripe e resfriado comuns, como feb...",Sintomas da gripe e resfriado comuns | como fe...,"[Sintomas da gripe e resfriado comuns, como fe...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Ácido acetilsalicílico + cafeína,N02B – Analgésicos e antipiréticos,Comprimido,650 + 65 mg,Dores moderadas a fortes.,Dores moderadas a fortes,[Dores moderadas a fortes],0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Ácido acetilsalicílico + maleato de clorfenira...,N02B – Analgésicos e antipiréticos,Cápsula dura,"324 + 2 + 32,4 mg","Sintomas da gripe e resfriado comuns, como feb...",Sintomas da gripe e resfriado comuns | como fe...,"[Sintomas da gripe e resfriado comuns, como fe...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,Ácido acetilsalicílico + maleato de dexclorfen...,N02B – Analgésicos e antipiréticos,Comprimido,400 + 1 + 10 + 30 mg,"Sintomas da gripe e resfriado comuns, como feb...",Sintomas da gripe e resfriado comuns | como fe...,"[Sintomas da gripe e resfriado comuns, como fe...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,Ácido acetilsalicílico + paracetamol + cafeína,N02B – Analgésicos e antipiréticos,Comprimido revestido,250 + 250 + 65 mg,"Dores leves a moderadas, incluindo as associad...",Dores leves a moderadas | incluindo as associa...,"[Dores leves a moderadas, incluindo as associa...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,Ácido azeláico,D10A – Preparações antiacne de uso local,Creme dermatológico,200 mg/g,Acne vulgar.,Acne vulgar,[Acne vulgar],1,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Ácido azeláico,D10A – Preparações antiacne de uso local,Gel dermatológico,150 mg/g,Acne vulgar. Rosácea papulopustulosa.,Acne vulgar | Rosácea papulopustulosa,"[Acne vulgar, Rosácea papulopustulosa]",1,0,0,...,0,0,0,0,0,0,0,0,0,0
16,Ácido benzóico + ácido salicílico + iodo metálico,D01A – Antifúngicos de uso local,Solução dermatológica,"20 + 20 + 2,5 mg/mL",Micoses superficiais da pele.,Micoses superficiais da pele,[Micoses superficiais da pele],0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,Ácido bórico + ácido salicílico + enxofre + óx...,D01A – Antifúngicos de uso local,Pó dermatológico,"3,0 + 0,352 + 17,602 + 11,735 g",Dermatite de fraldas. Brotoeja. Desodorante e ...,Dermatite de fraldas | Brotoeja | Desodorante ...,"[Dermatite de fraldas, Brotoeja, Desodorante e...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Ácido salicílico,D11A – Outras preparações dermatológicas,Gel dermatológico,270 mg/g,Tratamento e remoção das verrugas comuns.,Tratamento e remoção das verrugas comuns,[Tratamento e remoção das verrugas comuns],0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,Ácido undecilênico + undecilenato de sódio + á...,D01A – Antifúngicos de uso local,Solução dermatológica,"40 + 150 + 30 + 50 + 0,5 mg/mL",Micoses superficiais de pele e unha.,Micoses superficiais de pele e unha,[Micoses superficiais de pele e unha],0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,Ácido undecilênico + undecilenato de zinco + p...,D01A – Antifúngicos de uso local,Pó dermatológico,"2 + 150 + 60 + 0,5 mg/g","Micoses de pele, frieira, de unha, vulvar e pe...",Micoses de pele | frieira | de unha | vulvar e...,"[Micoses de pele, frieira, de unha, vulvar e p...",0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,Alantoína + triclosana + óxido de zinco,D01A – Antifúngicos de uso local,Pó dermatológico,5 + 1 + 100 mg/g,"Dermatite de fraldas. Eczemas, brotoejas, quei...",Dermatite de fraldas | Eczemas | brotoejas | q...,"[Dermatite de fraldas, Eczemas, brotoejas, que...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,Álcool polivinílico,S01X – Outros produtos oftalmológicos,Solução oftálmica,14 mg/mL,Lubrificante oftálmico / lágrima artificial.,Lubrificante oftálmico / lágrima artificial,[Lubrificante oftálmico / lágrima artificial],0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Alfaestradiol,G03C – estrógenos,Solução capilar,"0,25 mg/ml",Tratamento e prevenção da alopecia androgenética.,Tratamento e prevenção da alopecia androgenética,[Tratamento e prevenção da alopecia androgenét...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,Alginato de sódio + bicarbonato de potássio,A02A – Antiácidos,Suspensão oral,100 + 20 mg/mL,"Alívio da regurgitação ácida, azia e dor de es...",Alívio da regurgitação ácida | azia e dor de e...,"[Alívio da regurgitação ácida, azia e dor de e...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,Alginato de sódio + bicarbonato de sódio + car...,A02A – Antiácidos,Comprimido mastigável,"250 + 106,5 + 187,5 mg","Alívio da azia, dor de estômago devido à má di...",Alívio da azia | dor de estômago devido à má d...,"[Alívio da azia, dor de estômago devido à má d...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,Alginato de sódio + bicarbonato de sódio + car...,A02A – Antiácidos,Suspensão oral,"50 + 21,3 + 32,5 mg/mL","Alívio da azia, dor de estômago devido à má di...",Alívio da azia | dor de estômago devido à má d...,"[Alívio da azia, dor de estômago devido à má d...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,Bacillus cereus,A07F – Microrganismos antidiarreicos,Suspensão oral,1 X 10^6 end/mL,Coadjuvante no tratamento da diarreia; coadjuv...,Coadjuvante no tratamento da diarreia; coadjuv...,[Coadjuvante no tratamento da diarreia; coadju...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,Bicarbonato de sódio + carbonato de magnésio +...,A02A – Antiácidos,Granulado,"586,742 + 134,34 + 134,34 + 32,495 mg/g",Alívio da azia e dor de estômago devido à má d...,Alívio da azia e dor de estômago devido à má d...,[Alívio da azia e dor de estômago devido à má ...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Bicarbonato de sódio + carbonato de magnésio +...,A02A – Antiácidos,Pastilha,"63,7 + 67 + 521 + 3,3 mg",Alívio da azia e dor de estômago devido à má d...,Alívio da azia e dor de estômago devido à má d...,[Alívio da azia e dor de estômago devido à má ...,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
df_final.to_csv("tabela_anvisa_limpa.csv", index=False, sep=";", encoding="utf-8-sig")

## Inserindo os dados no banco

In [38]:
import pandas as pd
import unicodedata
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session
import config

engine = create_engine(config.conexao_banco)

# ---------------------------
# NORMALIZAÇÃO
# ---------------------------

def normalizar(txt):
    if pd.isna(txt):
        return None
    txt = unicodedata.normalize("NFKD", str(txt))
    txt = txt.encode("ASCII", "ignore").decode("ASCII")
    return txt.strip().title()

# ---------------------------
# GET OR CREATE
# ---------------------------

def get_or_create_sintoma(sessao, nome):
    nome = normalizar(nome)

    row = sessao.execute(
        text("SELECT idsintoma FROM sintoma WHERE nomeSintoma = :n"),
        {"n": nome}
    ).fetchone()

    if row:
        return row[0]

    res = sessao.execute(
        text("INSERT INTO sintoma (nomeSintoma) VALUES (:n)"),
        {"n": nome}
    )
    return res.lastrowid


def get_or_create_substancia(sessao, nome, subgrupo):
    nome = normalizar(nome)
    subgrupo = normalizar(subgrupo)

    row = sessao.execute(
        text("""
            SELECT idsubstancia, sugrupo
            FROM substancia
            WHERE nomeSubstancia = :n
        """),
        {"n": nome}
    ).fetchone()

    # já existe
    if row:
        id_sub, sugrupo_atual = row

        # se ainda não tem subgrupo salvo, atualiza
        if not sugrupo_atual and subgrupo:
            sessao.execute(
                text("""
                    UPDATE substancia
                    SET sugrupo = :s
                    WHERE idsubstancia = :id
                """),
                {"s": subgrupo, "id": id_sub}
            )

        return id_sub

    # não existe → cria já com subgrupo
    res = sessao.execute(
        text("""
            INSERT INTO substancia (nomeSubstancia, sugrupo)
            VALUES (:n, :s)
        """),
        {"n": nome, "s": subgrupo}
    )
    return res.lastrowid



def relacionar(sessao, idsintoma, idsubstancia):
    existe = sessao.execute(
        text("""
            SELECT 1
            FROM sintoma_has_substancia
            WHERE idsintoma = :s AND idsubstancia = :sub
        """),
        {"s": idsintoma, "sub": idsubstancia}
    ).fetchone()

    if not existe:
        sessao.execute(
            text("""
                INSERT INTO sintoma_has_substancia (idsintoma, idsubstancia)
                VALUES (:s, :sub)
            """),
            {"s": idsintoma, "sub": idsubstancia}
        )

# ---------------------------
# IMPORTAÇÃO CSV
# ---------------------------

df = pd.read_csv(
    "/home/mgabriel4/Documentos/GitHub/inter-4sem-2025-medicamentos/tabela_anvisa_limpa.csv",
    sep=";"
)

# coluna que representa a substância
coluna_substancia = "Fármaco"

# colunas que NÃO são sintomas
colunas_descartar = {
    "Fármaco",
    "Subgrupo terapêutico ou farmacológico",
    "Forma farmacêutica",
    "Concentração máxima",
    "Indicação terapêutica simplificada",
    "indicacao_limpa",
    "indicacoes_list"
}

# sintomas = todas as colunas que sobraram
sintomas = [c for c in df.columns if c not in colunas_descartar]

print(f"🧪 Total de sintomas detectados: {len(sintomas)}")

with Session(engine) as sessao, sessao.begin():
    for _, linha in df.iterrows():
        nome_sub = linha[coluna_substancia]
        subgrupo = linha["Subgrupo terapêutico ou farmacológico"]

        id_sub = get_or_create_substancia(sessao, nome_sub, subgrupo)

        for sintoma in sintomas:
            valor = linha[sintoma]

            if valor == 1:
                id_s = get_or_create_sintoma(sessao, sintoma)
                relacionar(sessao, id_s, id_sub)

print("✅ Importação concluída com sucesso!")

🧪 Total de sintomas detectados: 210
✅ Importação concluída com sucesso!