In [20]:
import pandas as pd
import re
import unicodedata

df = pd.read_csv("./base_filtrada_com_marcaLab.csv")

df['Forma farmacêutica'].unique()

array(['Comprimido', 'Cápsula gelatinosa mole, comprimido',
       'Comprimido, comprimido efervescente', 'Comprimido efervescente',
       'Comprimido efervescente, granulado',
       'Cápsula dura de liberação prolongada', 'Solução oral'],
      dtype=object)

In [21]:
def limpar_texto(t):
    if pd.isna(t):
        return ""
    t = str(t).lower().strip()
    # acentos
    t = unicodedata.normalize("NFKD", t)
    t = "".join(c for c in t if not unicodedata.combining(c))
    # facilitar o match
    t = t.replace("mg", " mg")
    t = t.replace("ml", " ml")
    t = t.replace("-", " ")
    t = " ".join(t.split())
    t = t.encode("ascii", errors="ignore").decode("utf-8")
    return t

df["forma_farmaceutica"] = df["Forma farmacêutica"].apply(limpar_texto)

df["forma_farmaceutica"].unique()

array(['comprimido', 'capsula gelatinosa mole, comprimido',
       'comprimido, comprimido efervescente', 'comprimido efervescente',
       'comprimido efervescente, granulado',
       'capsula dura de liberacao prolongada', 'solucao oral'],
      dtype=object)

In [ ]:
def categorizar_forma(texto):
    if pd.isna(texto):
        return "outros"
    t = texto.lower()

    if "comprim" in t:
        return "comprimido"
    if "caps" in t:
        return "capsula"
    if "xarope" in t:
        return "xarope"
    if "solu" in t:
        return "solucao"
    if "got" in t:
        return "gotas"
    if "pomad" in t:
        return "pomada"
    if "creme" in t:
        return "creme"
    if "gel" in t:
        return "gel"
    
    return "outros"

df["forma_farmaceutica"] = df["forma_farmaceutica"].apply(categorizar_forma)

In [23]:
df["forma_farmaceutica"].unique()

array(['comprimido', 'capsula', 'solucao'], dtype=object)

In [ ]:
df.head()

,idMedicamentos,nomeMedicamento,Subgrupo terapêutico ou farmacológico,preco,marca,quantidade,dosagem,Forma farmacêutica,substancia,substancia_limpa,...,vulvar_e_peniana,vomito_e_distensao_abdominal,ulcera_cutanea,subgrupo,subgrupo_desejado,idmarca,nomeMarca,laboratorio,nomeLaboratorio,forma_farmaceutica
0,33,AAS Ácido Acetilsalicílico 100mg Infantil 30 c...,N02B – Analgésicos e antipiréticos,25.69,14,30 Comprimidos,100MG,Comprimido,Ácido Acetilsalicílico,acido acetilsalicilico,...,0,0,0,n02b analgesicos e antipireticos,True,14,Acido Acetilsalicilico,12,EMS,comprimido
1,34,AAS Ácido Acetilsalicílico 100mg Infantil 120 ...,N02B – Analgésicos e antipiréticos,93.12,14,120 Comprimidos,100MG,Comprimido,Ácido Acetilsalicílico,acido acetilsalicilico,...,0,0,0,n02b analgesicos e antipireticos,True,14,Acido Acetilsalicilico,12,EMS,comprimido
2,35,Ácido Acetilsalicílico 100mg Infantil Sabor Mo...,N02B – Analgésicos e antipiréticos,4.79,15,30 Comprimidos,100MG,Comprimido,Ácido Acetilsalicílico,acido acetilsalicilico,...,0,0,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido
3,36,Ácido Acetilsalicílico 100mg 100 comprimidos E...,N02B – Analgésicos e antipiréticos,37.79,15,100 Comprimidos,100MG,Comprimido,Ácido Acetilsalicílico,acido acetilsalicilico,...,0,0,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido
4,37,Ácido Acetilsalicílico Infantil 100mg 10 compr...,N02B – Analgésicos e antipiréticos,2.89,15,10 Comprimidos,100MG,Comprimido,Ácido Acetilsalicílico,acido acetilsalicilico,...,0,0,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido

In [25]:
df = df.drop('Forma farmacêutica', axis=1)

In [26]:
df.head()

,idMedicamentos,nomeMedicamento,Subgrupo terapêutico ou farmacológico,preco,marca,quantidade,dosagem,substancia,substancia_limpa,avaliacao,...,vulvar_e_peniana,vomito_e_distensao_abdominal,ulcera_cutanea,subgrupo,subgrupo_desejado,idmarca,nomeMarca,laboratorio,nomeLaboratorio,forma_farmaceutica
0,33,AAS Ácido Acetilsalicílico 100mg Infantil 30 c...,N02B – Analgésicos e antipiréticos,25.69,14,30 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,3.8,...,0,0,0,n02b analgesicos e antipireticos,True,14,Acido Acetilsalicilico,12,EMS,comprimido
1,34,AAS Ácido Acetilsalicílico 100mg Infantil 120 ...,N02B – Analgésicos e antipiréticos,93.12,14,120 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.5,...,0,0,0,n02b analgesicos e antipireticos,True,14,Acido Acetilsalicilico,12,EMS,comprimido
2,35,Ácido Acetilsalicílico 100mg Infantil Sabor Mo...,N02B – Analgésicos e antipiréticos,4.79,15,30 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.2,...,0,0,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido
3,36,Ácido Acetilsalicílico 100mg 100 comprimidos E...,N02B – Analgésicos e antipiréticos,37.79,15,100 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.6,...,0,0,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido
4,37,Ácido Acetilsalicílico Infantil 100mg 10 compr...,N02B – Analgésicos e antipiréticos,2.89,15,10 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,3.3,...,0,0,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido

In [28]:
def excecao(texto):
    if (df['quantidade'] == '20ml') and (df['dosagem'] == '0MG'):
        if 'gotas' in df['nomeMedicamento'].str.lower():
            return 'gotas'
    return df['forma_farmaceutica']

df["forma_farmaceutica"] = df.apply(
    lambda row: "gotas"
    if (row.get("quantidade") == "20ml"
        and row.get("dosagem") == "0MG"
        and "gotas" in str(row.get("nomeMedicamento", "")).lower())
    else row["forma_farmaceutica"],
    axis=1,
)

In [29]:
df["forma_farmaceutica"].unique()

array(['comprimido', 'gotas', 'capsula', 'solucao'], dtype=object)

In [46]:
# ...existing code...
df["dosagem_num"] = (
    df["dosagem"]
    .str.extract(r"(\d+\,?\d*\.?\d*)")[0]
    .str.replace(",", ".")  # Replace comma with dot
    .astype(float)
)

df["dosagem_num"]

0       100.00
1       100.00
2       100.00
3       100.00
4       100.00
         ...
1597      6.00
1598      6.66
1599     20.00
1600     13.30
1601     13.30
Name: dosagem_num, Length: 1602, dtype: float64

In [40]:
def extrair_unidade(texto):
    if pd.isna(texto):
        return None
    t = texto.lower()
    if "mg" in t:
        return "mg"
    if re.search(r"\bg\b", t):
        return "g"
    if "ml" in t:
        return "ml"
    return "outros"

df["dosagem_unidade"] = df["dosagem"].apply(extrair_unidade)

In [42]:
df.head()

,idMedicamentos,nomeMedicamento,Subgrupo terapêutico ou farmacológico,preco,marca,quantidade,dosagem,substancia,substancia_limpa,avaliacao,...,ulcera_cutanea,subgrupo,subgrupo_desejado,idmarca,nomeMarca,laboratorio,nomeLaboratorio,forma_farmaceutica,dosagem_num,dosagem_unidade
0,33,AAS Ácido Acetilsalicílico 100mg Infantil 30 c...,N02B – Analgésicos e antipiréticos,25.69,14,30 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,3.8,...,0,n02b analgesicos e antipireticos,True,14,Acido Acetilsalicilico,12,EMS,comprimido,100.0,mg
1,34,AAS Ácido Acetilsalicílico 100mg Infantil 120 ...,N02B – Analgésicos e antipiréticos,93.12,14,120 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.5,...,0,n02b analgesicos e antipireticos,True,14,Acido Acetilsalicilico,12,EMS,comprimido,100.0,mg
2,35,Ácido Acetilsalicílico 100mg Infantil Sabor Mo...,N02B – Analgésicos e antipiréticos,4.79,15,30 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.2,...,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido,100.0,mg
3,36,Ácido Acetilsalicílico 100mg 100 comprimidos E...,N02B – Analgésicos e antipiréticos,37.79,15,100 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.6,...,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido,100.0,mg
4,37,Ácido Acetilsalicílico Infantil 100mg 10 compr...,N02B – Analgésicos e antipiréticos,2.89,15,10 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,3.3,...,0,n02b analgesicos e antipireticos,True,15,Advil,13,Haleon,comprimido,100.0,mg

In [48]:
df["quantidade_num"] = (
    df["quantidade"]
    .str.extract(r"(\d+)")
    .astype(float)
)

df["quantidade_num"]

0        30.0
1       120.0
2        30.0
3       100.0
4        10.0
        ...
1597    100.0
1598    150.0
1599    120.0
1600    240.0
1601    120.0
Name: quantidade_num, Length: 1602, dtype: float64

In [50]:
def tipo_quantidade(row):
    forma = row["forma_farmaceutica"]
    t = str(row["quantidade"]).lower()

    if forma in ["comprimido", "capsula", "tablet", "drágea", "sache"]:
        return "unidades"

    if forma in ["xarope", "solucao", "gotas", "ml"]:
        return "ml"

    if forma in ["pomada", "creme", "gel"]:
        return "g"

    return "outros"

df["quantidade_tipo"] = df.apply(tipo_quantidade, axis=1)

In [57]:
# valores distintos (equivalente a SELECT DISTINCT)
df["quantidade_tipo"].drop_duplicates().reset_index(drop=True)

# se quiser ver também a contagem de cada tipo
df["quantidade_tipo"].value_counts()

quantidade_tipo
unidades    1494
ml           108
Name: count, dtype: int64

In [58]:
df.head()

,idMedicamentos,nomeMedicamento,Subgrupo terapêutico ou farmacológico,preco,marca,quantidade,dosagem,substancia,substancia_limpa,avaliacao,...,subgrupo_desejado,idmarca,nomeMarca,laboratorio,nomeLaboratorio,forma_farmaceutica,dosagem_num,dosagem_unidade,quantidade_num,quantidade_tipo
0,33,AAS Ácido Acetilsalicílico 100mg Infantil 30 c...,N02B – Analgésicos e antipiréticos,25.69,14,30 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,3.8,...,True,14,Acido Acetilsalicilico,12,EMS,comprimido,100.0,mg,30.0,unidades
1,34,AAS Ácido Acetilsalicílico 100mg Infantil 120 ...,N02B – Analgésicos e antipiréticos,93.12,14,120 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.5,...,True,14,Acido Acetilsalicilico,12,EMS,comprimido,100.0,mg,120.0,unidades
2,35,Ácido Acetilsalicílico 100mg Infantil Sabor Mo...,N02B – Analgésicos e antipiréticos,4.79,15,30 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.2,...,True,15,Advil,13,Haleon,comprimido,100.0,mg,30.0,unidades
3,36,Ácido Acetilsalicílico 100mg 100 comprimidos E...,N02B – Analgésicos e antipiréticos,37.79,15,100 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,4.6,...,True,15,Advil,13,Haleon,comprimido,100.0,mg,100.0,unidades
4,37,Ácido Acetilsalicílico Infantil 100mg 10 compr...,N02B – Analgésicos e antipiréticos,2.89,15,10 Comprimidos,100MG,Ácido Acetilsalicílico,acido acetilsalicilico,3.3,...,True,15,Advil,13,Haleon,comprimido,100.0,mg,10.0,unidades

In [64]:
df.to_csv("./base_filtrada_com_marcaLab_e_formaFarmaceutica.csv", index=False)

metricas de custo por ml/mg

In [ ]:
# mask = df["quantidade_tipo"] == "unidades"
# df.loc[mask, "custo_por_mg"] = df.loc[mask, "preco"] / (df.loc[mask, "dosagem_num"] * df.loc[mask, "quantidade_num"])

In [ ]:
# mask = df["quantidade_tipo"] == "ml"
# df.loc[mask, "custo_por_ml"] = df.loc[mask, "preco"] / df.loc[mask, "quantidade_num"]